// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureSensor;

#nullable disable

namespace TemperatureSensor.Migrations
{
    [DbContext(typeof(TemperatureInfoContext))]
    [Migration("20231004122218_addingStateLimiteToTemperature")]
    partial class addingStateLimiteToTemperature
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TemperatureSensor.Entities.StateLimit", b =>
                {
                    b.Property<int>("StateLimitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("StateLimitsId");

                    b.ToTable("StateLimits");
                });

            modelBuilder.Entity("TemperatureSensor.Entities.TemperatureInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StateLimitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Temperature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StateLimitId");

                    b.ToTable("TemperatureInfos");
                });

            modelBuilder.Entity("TemperatureSensor.Entities.TemperatureInfo", b =>
                {
                    b.HasOne("TemperatureSensor.Entities.StateLimit", "StateLimit")
                        .WithMany()
                        .HasForeignKey("StateLimitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateLimit");
                });
#pragma warning restore 612, 618
        }
    }
}
