// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TemperatureSensor;

#nullable disable

namespace TemperatureSensor.Migrations
{
    [DbContext(typeof(TemperatureInfoContext))]
    partial class TemperatureInfoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("TemperatureSensor.Entities.StateLimit", b =>
                {
                    b.Property<int>("StateLimitsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("StateLimitsId");

                    b.ToTable("StateLimits");

                    b.HasData(
                        new
                        {
                            StateLimitsId = 1,
                            Name = "COLD",
                            Value = 19
                        },
                        new
                        {
                            StateLimitsId = 2,
                            Name = "WARM",
                            Value = 30
                        },
                        new
                        {
                            StateLimitsId = 3,
                            Name = "HOT",
                            Value = 30
                        });
                });

            modelBuilder.Entity("TemperatureSensor.Entities.TemperatureInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Temperature")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("TemperatureInfos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3261),
                            State = "COLD",
                            Temperature = 18
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3303),
                            State = "WARM",
                            Temperature = 24
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3305),
                            State = "WARM",
                            Temperature = 30
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3308),
                            State = "WARM",
                            Temperature = 26
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3309),
                            State = "HOT",
                            Temperature = 34
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3311),
                            State = "WARM",
                            Temperature = 24
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3313),
                            State = "WARM",
                            Temperature = 30
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3316),
                            State = "WARM",
                            Temperature = 26
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3318),
                            State = "HOT",
                            Temperature = 34
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3320),
                            State = "COLD",
                            Temperature = 8
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3321),
                            State = "COLD",
                            Temperature = 18
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3324),
                            State = "WARM",
                            Temperature = 24
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3326),
                            State = "WARM",
                            Temperature = 30
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3328),
                            State = "WARM",
                            Temperature = 26
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3330),
                            State = "HOT",
                            Temperature = 34
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3332),
                            State = "COLD",
                            Temperature = 18
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3334),
                            State = "COLD",
                            Temperature = 2
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3336),
                            State = "COLD",
                            Temperature = 6
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3338),
                            State = "HOT",
                            Temperature = 40
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3339),
                            State = "WARM",
                            Temperature = 25
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3341),
                            State = "COLD",
                            Temperature = 18
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3343),
                            State = "HOT",
                            Temperature = 47
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3345),
                            State = "HOT",
                            Temperature = 38
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3347),
                            State = "COLD",
                            Temperature = 14
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3349),
                            State = "COLD",
                            Temperature = 15
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3351),
                            State = "HOT",
                            Temperature = 36
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3353),
                            State = "COLD",
                            Temperature = 18
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3355),
                            State = "WARM",
                            Temperature = 27
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2023, 10, 4, 15, 3, 8, 379, DateTimeKind.Local).AddTicks(3356),
                            State = "HOT",
                            Temperature = 50
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
